# This is a basic workflow to help you get started with Actions

name: Stage2

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_call:
    inputs:
      inputstring:
        type: string
        description: cough
        required: true
        default: SDSGGNWKJ
      inputbase:
        type: number
        description: shut up
        required: true
        default: 9

  workflow_dispatch:
    inputs:
      inputstring:
        type: string
        description: cough
        required: true
        default: SDSGGNWKJ
      inputbase:
        type: number
        description: shut up
        required: true
        default: 9

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "6.0.x"

      - name: Restore
        run: dotnet restore

      - name: Run a one-line script
        run: dotnet build --no-restore

      - name: diagnostic
        run: echo input is ${{ inputs.inputstring }}

      - name: run it
        run: echo ${{ inputs.inputstring }} ${{ inputs.inputbase }} | dotnet run
